---
- name: Lookup OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Run OS specific tasks
  include: "setup-{{ ansible_os_family }}.yml"

# Make sure mnesia folder is there for rabbitmq:
- name: Create mnesia folder
  file:
    path: "{{ mnesia_base }}"
    state: directory
    owner: rabbitmq
    group: rabbitmq
    setype: rabbitmq_var_lib_t
  notify: Restart rabbitmq

- name: Set sebool for nis
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes
  when: (ansible_selinux != false) and (ansible_selinux.status == 'enabled')

- name: Update rabbitmq-env.conf
  template:
    src: etc/rabbitmq/rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: 644
    owner: root
    group: root
    backup: yes
  notify: Restart rabbitmq

# Store the erlang cookie in a different place to see if it changed
# if the cookie file changed, rabbit has to be stopped before it is changed
- name: Update erlang cookie control file
  template:
    src: erlang.cookie.j2
    dest: "{{ erlang_cookie_file }}.control"
    mode: 600
    owner: rabbitmq
    group: rabbitmq
    backup: yes
  register: erlang_cookie_control

- name: Stop rabbitmq before erlang cookie changed
  service:
    name: rabbitmq-server
    state: stopped
    enabled: "{{ rabbitmq_service_enabled |default('yes') }}"
  when: erlang_cookie_control.changed

- name: Update erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ erlang_cookie_file }}"
    mode: 600
    owner: rabbitmq
    group:rabbitmq
    backup: yes
  notify: Restart rabbitmq
  when: erlang_cookie_control.changed

- name: Install rabbitmq plugins
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    new_only: yes
  with_items: "{{ rabbitmq_plugins }}"
  notify: Restart rabbitmq

- name: Update rabbitmq.conf
  template:
    src: etc/rabbitmq/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.config
    mode: 0755
    owner: root
    group: root
    backup: yes
  notify: Restart rabbitmq

- name: Update rabbitmq_defs.json
  template:
    src: etc/rabbitmq/rabbitmq_defs.json.j2
    dest: /etc/rabbitmq/rabbitmq_defs.json
    mode: 0755
    owner: root
    group: root
    backup: yes
  notify: Restart rabbitmq
