---
- name: Install erlang
  yum:
    name: erlang

- name: Check if rabbitmq is installed
  command: rabbitmqctl status
  register: is_installed
  ignore_errors: True
  changed_when: False

- name: Test rabbitmq version
  shell: "rpm -qv rabbitmq-server --queryformat '%{VERSION}\n'"
  register: has_version
  ignore_errors: True
  when: is_installed|success
  changed_when: False

- name: Download rabbitmq rpm locally
  local_action:
    module: get_url
    url: "http://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version[:-2] }}/rabbitmq-server-{{ rabbitmq_version }}.noarch.rpm"
    dest: "/tmp/rabbitmq-server-{{ rabbitmq_version }}.noarch.rpm"
  become: False
  when: is_installed|failed or has_version.stout is defined and has_version.stdout != rabbitmq_version

- name: Upload rpm to remote system
  copy:
    src: "/tmp/rabbitmq-server-{{ rabbitmq_version }}.noarch.rpm"
    dest: /tmp
  when: is_installed|failed or has_version.stout is defined and has_version.stdout != rabbitmq_version

- name: Install rabbitmq rpm
  yum:
    name: "/tmp/rabbitmq-server-{{ rabbitmq_version }}.noarch.rpm"
    disablerepo: "*"
  notify: Restart rabbitmq
  when: is_installed|failed or has_version.stout is defined and has_version.stdout != rabbitmq_version
